// Business glossary — definitions shown on hover anywhere via <InfoTerm>
export const TERMS: Record<string, string> = {
  CLTV: "Customer Lifetime Value — the total revenue a business can reasonably expect from a single customer account over the entire span of the relationship.",
  "Predicted CLTV": "Model-projected lifetime value based on engagement, purchase frequency, and retention probability.",
  "Retention Rate": "Percentage of customers a business keeps over a given period. Higher is better.",
  "Churn Rate": "Percentage of customers who stopped buying or cancelled in a period. Lower is better.",
  "Customer Equity": "The sum of the lifetime values of all customers — a measure of total customer-base worth.",
  "Repeat Purchase Rate": "Share of customers who have made more than one purchase. A leading indicator of loyalty.",
  "Purchase Frequency": "Average number of orders a customer places per year.",
  "Customer Tenure": "Average length of the customer relationship, typically measured in months.",
  "Revenue Retention": "Revenue retained from existing customers compared to a prior period — net of churn and expansion.",
  "Revenue at Risk": "Revenue tied to customers showing high churn probability (>60%) that has not yet been lost.",
  Cohort: "A group of customers who started in the same period — used to compare retention across time.",
  "Churn Probability": "Model-estimated likelihood (0–100%) that a customer will stop purchasing in the next period.",
  "Retention Score": "Composite score (0–100) reflecting how likely a customer is to stay, based on engagement and behavior signals.",
  "Engagement Score": "Behavioral score combining login activity, feature usage, communication response, and order cadence.",
  RFM: "Recency, Frequency, Monetary — a classic segmentation framework: how recently, how often, and how much a customer buys.",
  Recency: "Days since the customer's last purchase.",
  Frequency: "How often a customer purchases over a given period.",
  Monetary: "Total revenue a customer has generated.",
  Champions: "Best customers — recent, frequent, and high-spending. Top retention priority.",
  "Loyal Customers": "Repeat buyers with strong engagement, though not always the highest spenders.",
  "Potential Loyalists": "Recent customers with above-average frequency — prime targets to nurture into loyalists.",
  "At Risk": "Previously valuable customers whose engagement is declining — proactive retention recommended.",
  "Lost Customers": "Customers with no recent activity who are effectively churned.",
  "Drop-off Rate": "Percentage of customers who fail to advance from one journey stage to the next.",
  "Conversion Rate": "Percentage of customers who complete a target action (e.g. first purchase, repeat purchase).",
  "Feature Importance": "Relative contribution of each input feature to a model's predictions.",
  "Model Accuracy": "How often a predictive model's outputs match observed outcomes on held-out data.",
  Segment: "A grouping of customers who share key characteristics (industry, size, behavior, value).",
};
